#!/usr/bin/env node
/**
 * Generate examples/website/src/content.ts from real project files.
 *
 * Reads selected files from the repo and emits a TypeScript module
 * exporting VFS_FILES — the virtual filesystem seed for the website.
 *
 * Usage:
 *   node scripts/generate-content.mjs
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const OUTPUT = resolve(ROOT, 'examples/website/src/content.ts');

// Files to include in the VFS, mapped from repo paths to VFS paths.
// If the repo file doesn't exist, the entry is silently skipped.
const FILE_MAP = [
  { src: 'README.md', vfs: '/home/user/README.md', maxLines: 80 },
  { src: 'Cargo.toml', vfs: '/home/user/Cargo.toml', maxLines: 30 },
  { src: 'src/main.rs', vfs: '/home/user/src/main.rs' },
  { src: 'examples/fibonacci.sh', vfs: '/home/user/examples/fibonacci.sh' },
  { src: 'examples/word-count.sh', vfs: '/home/user/examples/word-count.sh' },
];

// Static entries that don't come from repo files
const STATIC_ENTRIES = {
  '/home/user/docs/architecture.md': `# Architecture Overview

rust-bash is organized into layered subsystems:

1. **Lexer/Parser** — Tokenizes bash input into an AST
2. **Interpreter** — Walks the AST, executing commands
3. **Virtual Filesystem** — In-memory file storage with path resolution
4. **Command System** — 80+ built-in commands (echo, grep, awk, etc.)
5. **Execution Safety** — Configurable limits on loops, output, time
6. **Integration Layer** — CLI, WASM, C FFI, and npm package

All file I/O goes through VirtualFs. No \`std::fs\` in command code.
All process execution is in-process. No \`std::process::Command\`.
`,
};

function escapeForTemplate(s) {
  // Escape backticks and ${...} for template literal embedding
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function truncateLines(content, maxLines) {
  if (!maxLines) return content;
  const lines = content.split('\n');
  if (lines.length <= maxLines) return content;
  return lines.slice(0, maxLines).join('\n') + '\n\n... (truncated)\n';
}

const entries = {};

for (const { src, vfs, maxLines } of FILE_MAP) {
  const absPath = resolve(ROOT, src);
  if (!existsSync(absPath)) {
    console.warn(`  skip (not found): ${src}`);
    continue;
  }
  let content = readFileSync(absPath, 'utf-8');
  content = truncateLines(content, maxLines);
  entries[vfs] = content;
}

// Merge static entries
Object.assign(entries, STATIC_ENTRIES);

// Generate TypeScript source
const lines = [
  '/**',
  ' * Preloaded file content for the virtual filesystem.',
  ' *',
  ' * AUTO-GENERATED by scripts/generate-content.mjs — do not edit manually.',
  ' */',
  '',
  'export const VFS_FILES: Record<string, string> = {',
];

for (const [path, content] of Object.entries(entries)) {
  lines.push(`  '${path}': \`${escapeForTemplate(content)}\`,`);
  lines.push('');
}

lines.push('};');
lines.push('');

writeFileSync(OUTPUT, lines.join('\n'));
console.log(`✅ Generated ${OUTPUT} (${Object.keys(entries).length} files)`);
