/* Auto-generated by cbindgen. Do not edit manually.
 * Regenerate with: cbindgen --config cbindgen.toml --crate rust-bash --output include/rust_bash.h
 */

#ifndef RUST_BASH_H
#define RUST_BASH_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// A sandboxed bash shell interpreter.
typedef struct RustBash RustBash;

// Result of executing a command via [`rust_bash_exec`].
//
// The `stdout_ptr`/`stderr_ptr` fields point to heap-allocated byte buffers whose
// lengths are given by `stdout_len`/`stderr_len`. The caller must free the entire
// result (including these buffers) by passing it to [`rust_bash_result_free`].
typedef struct ExecResult {
    const char *stdout_ptr;
    int32_t stdout_len;
    const char *stderr_ptr;
    int32_t stderr_len;
    int32_t exit_code;
} ExecResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Create a new sandboxed shell instance.
//
// If `config_json` is `NULL`, a default configuration is used. Otherwise it must
// point to a valid null-terminated UTF-8 JSON string conforming to the schema
// documented in the [module-level docs](self).
//
// Returns a heap-allocated `RustBash*` on success, or `NULL` on error. On error
// the reason is retrievable via [`rust_bash_last_error`].
//
// # Safety
//
// - `config_json`, if non-null, must point to a valid null-terminated C string.
// - The returned pointer must eventually be passed to [`rust_bash_free`].
struct RustBash *rust_bash_create(const char *config_json);

// Execute a shell command string in an existing sandbox.
//
// Returns a heap-allocated [`ExecResult`](CExecResult) on success, or `NULL` on error.
// On error the reason is retrievable via [`rust_bash_last_error`].
//
// # Safety
//
// - `sb` must be a non-null pointer previously returned by [`rust_bash_create`]
//   and not yet freed.
// - `command` must be a non-null pointer to a valid null-terminated C string.
// - The returned `ExecResult*` must eventually be passed to [`rust_bash_result_free`].
struct ExecResult *rust_bash_exec(struct RustBash *sb, const char *command);

// Free an [`ExecResult`](CExecResult) previously returned by [`rust_bash_exec`].
//
// If `result` is `NULL` this is a no-op.
//
// # Safety
//
// - `result` must be `NULL` or a pointer previously returned by [`rust_bash_exec`]
//   that has not yet been freed.
// - After this call the pointer is invalid and must not be dereferenced.
void rust_bash_result_free(struct ExecResult *result);

// Free a `RustBash*` handle previously returned by [`rust_bash_create`].
//
// If `sb` is `NULL` this is a no-op.
//
// # Safety
//
// - `sb` must be `NULL` or a pointer previously returned by [`rust_bash_create`]
//   that has not yet been freed.
// - After this call the pointer is invalid and must not be dereferenced.
void rust_bash_free(struct RustBash *sb);

// Return the library version as a static null-terminated string.
//
// The returned pointer is valid for the lifetime of the loaded library and must
// **not** be freed by the caller.
//
// # Safety
//
// The returned pointer points to static read-only memory.
const char *rust_bash_version(void);

// Retrieve the last error message for the current thread.
//
// Returns `NULL` if no error is stored (i.e. the last FFI call succeeded).
// The returned pointer is valid only until the next FFI call on the same thread.
// The caller must **not** free the returned pointer.
//
// # Safety
//
// The returned pointer (if non-null) points to thread-local storage and is
// invalidated by the next FFI call on the same thread.
const char *rust_bash_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RUST_BASH_H */
