/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmbash_free: (a: number, b: number) => void;
export const wasmbash_command_names: (a: number) => [number, number];
export const wasmbash_cwd: (a: number) => [number, number];
export const wasmbash_exec: (a: number, b: number, c: number) => [number, number, number];
export const wasmbash_exec_with_options: (a: number, b: number, c: number, d: any) => [number, number, number];
export const wasmbash_exists: (a: number, b: number, c: number) => number;
export const wasmbash_last_exit_code: (a: number) => number;
export const wasmbash_mkdir: (a: number, b: number, c: number, d: number) => [number, number];
export const wasmbash_new: (a: any) => [number, number, number];
export const wasmbash_read_file: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmbash_readdir: (a: number, b: number, c: number) => [number, number, number];
export const wasmbash_register_command: (a: number, b: number, c: number, d: any) => [number, number];
export const wasmbash_remove_dir_all: (a: number, b: number, c: number) => [number, number];
export const wasmbash_remove_file: (a: number, b: number, c: number) => [number, number];
export const wasmbash_stat: (a: number, b: number, c: number) => [number, number, number];
export const wasmbash_write_file: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasm_bindgen__closure__destroy__h01f82033f57c3cd2: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7a631768e569dc43: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const wasm_bindgen__convert__closures_____invoke__h888e266ba1af605a: (a: number, b: number, c: number, d: number, e: any) => [number, number, number];
export const wasm_bindgen__convert__closures_____invoke__h556d52e4eb39cbb5: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasm_bindgen__convert__closures_____invoke__ha3337c50045b27fb: (a: number, b: number, c: number, d: number) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
